# -*- coding: utf-8 -*-
"""HW03_group6_tsne03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lpkj4HgVXrBr5dyoxZ5gXu_v6ogyfVFT
"""

import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt

#建立資料

#建立表格
df = pd.DataFrame(columns = ['Class', 'Drink', 'Rank', 'Num'])
#df

#Coke
for i in range(200):
  x = random.gauss(mu=100, sigma=200)
  new_row = [(1, 'Coke', 7, x)]
  dfnew = pd.DataFrame(new_row, columns = ['Class', 'Drink', 'Rank', 'Num'])
  df = df.append(dfnew, ignore_index=True)

#Pepsi
for i in range(100):
  x = random.gauss(mu=200, sigma=10)
  new_row = [(2, 'Pepsi', 6, x)]
  dfnew = pd.DataFrame(new_row, columns = ['Class', 'Drink', 'Rank', 'Num'])
  df = df.append(dfnew, ignore_index=True)

#7Up
for i in range(100):
  x = random.gauss(mu=200, sigma=10)
  new_row = [(3, '7Up', 5, x)]
  dfnew = pd.DataFrame(new_row, columns = ['Class', 'Drink', 'Rank', 'Num'])
  df = df.append(dfnew, ignore_index=True)

#Sprite
for i in range(200):
  x = random.gauss(mu=400, sigma=100)
  new_row = [(4, 'Sprite', 4, x)]
  dfnew = pd.DataFrame(new_row, columns = ['Class', 'Drink', 'Rank', 'Num'])
  df = df.append(dfnew, ignore_index=True)

#Latte
for i in range(100):
  x = random.gauss(mu=800, sigma=10)
  new_row = [(5, 'Latte', 3, x)]
  dfnew = pd.DataFrame(new_row, columns = ['Class', 'Drink', 'Rank', 'Num'])
  df = df.append(dfnew, ignore_index=True)

#Espresso
for i in range(100):
  x = random.gauss(mu=800, sigma=10)
  new_row = [(6, 'Espresso', 2, x)]
  dfnew = pd.DataFrame(new_row, columns = ['Class', 'Drink', 'Rank', 'Num'])
  df = df.append(dfnew, ignore_index=True)

#Cappuccino
for i in range(200):
  x = random.gauss(mu=900, sigma=400)
  new_row = [(7, 'Cappuccino', 1, x)]
  dfnew = pd.DataFrame(new_row, columns = ['Class', 'Drink', 'Rank', 'Num'])
  df = df.append(dfnew, ignore_index=True)

df

#轉換資料型態
df['Class'] = df['Class'].astype('int')
df['Rank'] = df['Rank'].astype('int')
df['Num'] = df['Num'].astype('float')

df.dtypes

#1-of-k

df_drink = pd.DataFrame(df['Drink'])
print(df_drink)

#Label encoding
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df_drink_label = df_drink.apply(labelencoder.fit_transform)
print(df_drink_label)

#One hot encoding
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
onehotencoder.fit(df_drink_label)
drink_onehot = onehotencoder.transform(df_drink_label).toarray()
print(drink_onehot.shape)
print(drink_onehot)
df_drink_onehot = pd.DataFrame(drink_onehot,columns = ['Drink_7Up', 'Drink_Cappuccino', 'Drink_Coke', 'Drink_Espresso', 'Drink_Latte', 'Drink_Pepsi', 'Drink_Sprite'])
print(df_drink_onehot)

#合併表格
df_ranknum = pd.DataFrame(df[['Rank', 'Num']])
print(df_ranknum)
df_oneofk = pd.concat([df_drink_onehot, df_ranknum], axis=1)
df_oneofk

#df_oneofk
#Y_data_class

from sklearn.manifold import TSNE
X_tsnea = TSNE(n_components=2).fit_transform(df_oneofk)
print(X_tsnea.shape)

# Commented out IPython magic to ensure Python compatibility.
# %pylab inline
figure(figsize=(11, 5))
cmap = plt.get_cmap('nipy_spectral')

types1 = df['Class'].unique()
type1_ids = df['Class'].unique()
num_types1 = len(types1)

subplot(1,2,1)
scatter(X_tsnea[:, 0], X_tsnea[:, 1], c=cmap(df['Class'] / num_types1))
title('TSNE')

df_class = pd.DataFrame(df['Class'])
df_class