# -*- coding: utf-8 -*-
"""hw3_HSR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12vHsZRj15WVTIzAG4EuH60by5UQeVYvg
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from matplotlib.collections import LineCollection
from sklearn import manifold
from sklearn.manifold import MDS
from sklearn.metrics import euclidean_distances
from sklearn.decomposition import PCA

#距離矩陣
from scipy.spatial import distance
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform
HSR = np.array([[25.048,121.517],[25.013,121.215]
        ,[24.808,121.040],[24.112,120.616],
        [23.734,120.417],[22.926,120.286],[22.687,120.308]])
dist=pdist(HSR,metric='euclidean')
dist_HSR = squareform(dist)
dist_HSR

model = MDS(n_components=2,dissimilarity='euclidean',random_state=1)
out = model.fit_transform(HSR)

annotations=["taipei","taoyuan","hsinchu","taichung","yulin",'tainan','kaohsiung']
plt.figure(figsize=(7,5))
plt.title("MDS_HSR Station",
      fontsize = 15, fontweight = "bold")
plt.scatter(out[:,0],out[:,1],s=50)
for i,label in  enumerate(annotations):
  plt.annotate(label, (out[i,0], out[i,1]))
plt.axis('equal')